package tiki.VM;

public enum Operator {
	ADD_F, ADD_I, ADD_R, AND_B, ARG, BSP, DIV_F, DIV_I, EQUAL_B, EQUAL_F, EQUAL_I, EQUAL_R, ESP, F2I, GREAT_F, GREAT_I, GREATE_F, GREATE_I, HALT, INVOKE, JUMP, LESS_F, LESS_I, LESSE_F, LESSE_I, LOCAL, MOD_I, MOV, MUL_F, MUL_I, NEW, NEWA, NOT, OR_B, REF, RET, RETV, SUB_F, SUB_I, SYSINVOKE, TRUEJUMP, UNEQUAL_B, UNEQUAL_F, UNEQUAL_I, UNEQUAL_R, VARARGS;
}
